# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    set_locale_from_accept_language: true
    set_content_language_from_locale: true
    default_locale: "%default_locale%"
    enabled_locales: ["en", "es"]

    secret: "%env(APP_SECRET)%"
    #csrf_protection: true
    http_method_override: false

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
        gc_probability: null,
        cookie_lifetime: 0

    esi: true
    fragments: { path: /_fragment }
    php_errors:
        log: true

    form:
        legacy_error_messages: false

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
